version: '3'

services:
  ipfs:
    image: ipfs/go-ipfs

  es:
    image: elasticsearch

  crawl:
    image: robcurrie/search-cgt
    links:
      - ipfs
      - es
    volumes:
      - ./pyensembl:/root/.cache/pyensembl
      - .:/usr/src/app
    entrypoint: python search-cgt/crawl.py -t 60 -i 1 QmWPSzKERs6KAjb8QfSXViFqyEUn3VZYYnXjgG6hJwXWYK

  search:
    image: robcurrie/search-cgt
    ports:
      - "5000:5000"
    links:
      - ipfs
      - es

    # Build and run out of local directory with auto-reload
    build: .
    volumes:
      - .:/usr/src/app
    entrypoint: uwsgi --ini uwsgi.ini --honour-stdin --python-autoreload=1 --processes=1 --threads=1
