version: '2'

volumes:
  ipfs:
    driver_opts:
      type: none
      device: /mnt/search/ipfs
      o: bind
  es:
    driver_opts:
      type: none
      device: /mnt/search/es
      o: bind
  ensembl:
    driver_opts:
      type: none
      device: /mnt/search/ensembl
      o: bind

services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.15
    volumes:
      - ipfs:/data/ipfs

  es:
    image: elasticsearch:5.3
    volumes:
      - es:/usr/share/elasticsearch/data

  crawl:
    image: cancergenetrust/search
    links:
      - ipfs
      - es
    volumes:
      - ./pyensembl:/root/.cache/pyensembl
      - .:/usr/src/app
    entrypoint: python searchcgt/crawl.py -t 60 -i 1 QmWPSzKERs6KAjb8QfSXViFqyEUn3VZYYnXjgG6hJwXWYK

  search:
    image: cancergenetrust/search
    ports:
      - "5001:5000"
    environment:
      - VIRTUAL_HOST=search.cancergenetrust.org
      - LETSENCRYPT_HOST=search.cancergenetrust.org
    links:
      - ipfs
      - es

    # Build and run out of local directory with auto-reload
    build: .
    volumes:
      - ensembl:/root/.cache/pyensembl
      - .:/usr/src/app
    command: --python-autoreload=1 --processes=1 --threads=1
