version: '2'

volumes:
  ipfs:
  es:
  ensembl:

services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.10
    volumes:
      - ipfs:/data/ipfs

  es:
    image: elasticsearch
    volumes:
      - es:/usr/share/elasticsearch/data

  crawl:
    image: cancergenetrust/search
    links:
      - ipfs
      - es
    volumes:
      - ./pyensembl:/root/.cache/pyensembl
      - .:/usr/src/app
    entrypoint: python searchcgt/crawl.py -t 60 -i 1 QmWPSzKERs6KAjb8QfSXViFqyEUn3VZYYnXjgG6hJwXWYK

  search:
    image: cancergenetrust/search
    ports:
      - "5000:5000"
    links:
      - ipfs
      - es

    # Build and run out of local directory with auto-reload
    build: .
    volumes:
      - ensembl:/root/.cache/pyensembl
      - .:/usr/src/app
    command: --python-autoreload=1 --processes=1 --threads=1
